sudo: false
language: php
php:
  - nightly
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

# Declare which versions of WordPress to test against.
# Also declare whether or not to test in Multisite.
env:
  # Trunk
  # @link https://github.com/WordPress/WordPress
  - WP_VERSION=master WP_MULTISITE=0
  - WP_VERSION=master WP_MULTISITE=1
  # WordPress 4.5
  # @link https://github.com/WordPress/WordPress/tree/4.5-branch
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=1

matrix:
  allow_failures:
    - php: nightly

